config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  authenticated :user do
      root to: "home#hello", as: "home"
  end
  unauthenticated :user do
      root 'welcome#index'
  end
  
  match 'home' => 'home#hello', :via=> :get
  
  resources :users
  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  
  validates :event_text, presence: true
  validates :time, presence: true
  
  self.per_page = 20
    
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: { maximum: 100 }
  validates :username, presence: true, length: { maximum: 20 }, :uniqueness => { case_sensitive: false }
  
  has_many :events
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
        where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :email, :encrypted_password])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :username, :remember_me])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!
    
    def create
        @event = Event.new(event_params) do |event|
            event.user = current_user
        end
        @event.save
    end
    
    def update
        @event = Event.find(params[:id])
        @event.update(event_params)
        redirect_to url_for(:controller => :home, :action => :hello)
    end
    
    def edit
        @event = Event.find(params[:id])
    end
    
    def destroy
        @event = Event.find(params[:id])
        @event_id = params[:id]
        flash[:notice] = "Deleted Event"
    end
    
    private
    def event_params
        params.require(:event).permit(:event_text, :time)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def hello
      @events = Event.where("user_id = ?", current_user).paginate(page: params[:page]).order('time DESC')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_action :set_user
    before_action :check_user, only: [:edit, :update, :destroy]
    before_action :authenticate_user!

    
    def show
        @events = @user.events.paginate(page: params[:page]).order('time DESC')
    end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to @user
        else
            render 'new'
        end
    end
    
    def destroy
    end
    
    private
    def user_params
        params.require(:user).permit(:name, :username, :email, :encrypted_password)
    end
    
    def check_user
        if @user != current_user
            redirect_to root_path
        end
    end
    
    def set_user
        @user = User.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
    def resource_name
        :user
    end
    
    def resource
        @resource ||= User.new
    end
    
    def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
    end
end

app/views/events/_event.html.erb
<div id="event-<%= event.id %>" class="micropost">
  <div class="content">
    <div class="post-content">
      <div class="post">
          <b>EVENT:</b> <%= event.event_text %>
      </div>
    </div>
    <div class="time-content">
        <span> <b>WHEN:</b> <%= event.time.to_formatted_s(:short) %></span>
    </div>
  </div>
  <div class="actions">
    <div class="actions-content">
      <% if event.user == current_user %>
        <%= link_to event_path(event), method: :delete, remote: true do %>
          <i class="fa fa-trash"></i>
        <% end %>
        <%= link_to 'Edit', edit_event_path(event) %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/create.js.erb
<% if @event.save %>
    $("#event_event_text").val("");
    $("#feed").prepend("<%=j render @event %>");
    $('#event-error').html("<%=j render 'partials/error_message', error_message: 'Event added to schedule' %>");
<% else %>
    $('#event-error').html("<%=j render 'partials/error_message', error_message: @event.errors.full_messages.first %>");
<% end %>

app/views/events/destroy.js.erb
<% if @event.destroy %>
  $("#event-<%= @event_id %>").remove();
  $("#notice").html("<%=j (flash[:notice]) %>");
<% else %>
  $('#event-error').html("<%=j render 'partials/error_message', error_message: 'Event deletion failed. Try again later' %>");
<% end %>

app/views/events/edit.html.erb
<%= form_for :event, url: event_path(@event), method: :patch do |f| %>
    <p>
        <%= f.label :text %><br>
        <%= f.text_area :event_text %>
    </p>

    <p> <%= f.submit %> </p>
<% end %>

app/views/home/hello.html.erb
<div class="col-lg-10 col-lg-offset-1">
<div class="row">
  <div class="col-lg-6">
    <div class="row">
      <div class="col-lg-12">
        <div class="well">
          <%= render 'partials/new_event', event_id: nil %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div id="feed" class="well feed">
          <%= render(@events) || "" %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chronos</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/navbar' %>
    <% unless notice.blank? %>
      <div class="alert alert-info alert-dismissable alert-fixed">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>
    <% unless alert.blank? %>
      <div class="alert alert-danger alert-dismissable alert-fixed">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/partials/_devise_form_errors.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
  	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= resource.errors.full_messages.first %>
  </div>
<% end %>

app/views/partials/_error_message.html.erb
<% if error_message %>
  <div class="alert alert-dismissable alert-fixed alert-info">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= error_message %>
  </div>
<% end %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Chronos", root_url, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <a href="#", class="profile-image dropdown-toggle" data-toggle="dropdown", role="button", aria-expanded="false"> Menu </a>
            <ul class="dropdown-menu">
              <li><%= link_to "#{current_user.name}<br><b>#{current_user.username}</b>".html_safe, user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Settings", user_path(current_user) %></li>
              <li><%= link_to('Sign out', destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
   </div>
  </div>
</nav>

app/views/partials/_new_event.html.erb
<%= form_tag events_path(parent_id: event_id), multipart: true, method: :post, remote: true do %>
    <div class="form-group">
        <%= text_area_tag "event[event_text]", nil, class: "form-control", placeholder: "Add a new event" %>
    </div>
    <div class="form-group">
        <%= datetime_field_tag "event[time]", nil, class: "form-control", placeholder: "Year, Month, Day, Hour" %>
    </div>
    <div class="form-group">
        <%= button_tag id: "Add Event", class: "btn btn-primary" do %>
            <%= fa_icon "bolt" %> Add Event
        <% end %>    
    </div>
<% end %>

app/views/users/show.html.erb
<div class="row">
    <div class="col-lg-10 col-lg-offset-1">
        <div id = "landing-content" class = "col-lg-9">
            <h2> Hello <%= @user.name %> </h2>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div id="feed" class="well feed">
                    <%= render(@events) || "" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-lg-10 col-lg-offset-1">
    <div class="row">
      <div id="landing-content" class="col-lg-9">
        <h3><b>Welcome to Chronos,</b></h3>
        <p>
          A scheduling app, built on Rails, designed to empower user time management.
        </p>
      </div>
        <div class="col-lg-3">
            <div class="row">
                <div class="well">
                    <%= render "devise/sessions/form" %>
                </div>
            </div>
            <div class="row">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Create an Account</h3>
                    </div>
                    <div class="panel-body">
                        <%= render "devise/registrations/form" %>
                    </div>
                </div>
            </div>
        </div>
    </div>
  </div
</div>